basePath: /license-manager/v1
definitions:
  utils.Response:
    properties:
      baseStatus:
        type: string
      data:
        type: object
      msg:
        type: string
      status:
        type: string
    type: object
info:
  contact:
    email: onesafe@163.com
  description: This is a doc describe API of License Manager
  license: {}
  title: License Manager API
  version: "0.1"
paths:
  /licenses:
    get:
      consumes:
      - application/json
      description: Get all licenses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
            type: object
      summary: Get all licenses
  /licenses/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload License File
      parameters:
      - description: license file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
            type: object
      summary: Upload License File
  /rsakeys:
    get:
      consumes:
      - application/json
      description: Generate rsa keys
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
            type: object
      summary: Generate rsa keys
swagger: "2.0"
