// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-09-03 16:57:37.0133489 +0800 CST m=+0.062334994

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is a doc describe API of License Manager",
        "title": "License Manager API",
        "contact": {
            "email": "onesafe@163.com"
        },
        "license": {},
        "version": "0.1"
    },
    "basePath": "/license-manager/v1",
    "paths": {
        "/daslicense": {
            "post": {
                "description": "Generate Das License",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Generate Das License",
                "parameters": [
                    {
                        "description": "Das license",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/swagtype.DasLicense"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/licenses": {
            "get": {
                "description": "Get all licenses",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get all licenses",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/licenses/upload": {
            "post": {
                "description": "Upload License File",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Upload License File",
                "parameters": [
                    {
                        "type": "file",
                        "description": "license file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/rsakeys": {
            "get": {
                "description": "Generate rsa keys",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Generate rsa keys",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "swagtype.DasLicense": {
            "type": "object",
            "properties": {
                "DiDiExpiredDate": {
                    "type": "string"
                },
                "expiredDate": {
                    "type": "string"
                },
                "maxCpuCores": {
                    "type": "integer"
                },
                "maxMemoryBytes": {
                    "type": "integer"
                },
                "product": {
                    "type": "string"
                },
                "versionsSupported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "baseStatus": {
                    "type": "string"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
